env:
  global:
  - DOCKER_REPO=quay.io/kubevirt
  - TAG=$TRAVIS_TAG
language: go
go_import_path: kubevirt.io/hostpath-provisioner-operator
go:
- 1.13.1
services:
- docker

install:
- go get -u github.com/mgechev/revive
before_script:
- make test
before_deploy:
- docker login quay.io -u="$QUAY_USER" -p="$QUAY_PASS"
deploy:
- provider: script
  env: TAG=latest
  script: make push
  skip_cleanup: true
  on:
    branch: master
    repo: kubevirt/hostpath-provisioner-operator
- provider: script
  script: make push
  branches:
    only: "/v[0-9]+\\.[0-9]+\\.[0-9]+(-alpha\\.[0-9]+){0,1}/"
  on:
    tags: true
    repo: kubevirt/hostpath-provisioner-operator
- provider: releases
  branches:
    only: "/v[0-9]+\\.[0-9]+\\.[0-9]+(-alpha\\.[0-9]+){0,1}/"
  on:
    tags: true
    repo: kubevirt/hostpath-provisioner-operator
  api_key:
    secure: "SFo0Id3ghKOyF85I0/Gvm7vDh34qaz3zV/gLGP43M+0t9B/GCkJXB+JRnxwUUn/cuKqId4tVTRhWOG4VhjXr46DcbCRObeapeEAG6zItuu5vxdE4ZdGf+VdM4LNjMNonNTFSSe8s4JH/sFfUo/IqAcyyB+GduI/nf3zZ90ia1TnvWuYACscAxKsj78E6Ppb8tudvwOfFOEv+2w9pIBlfdc6yYZyBhHmzeBRdUTuEdEZ/h7gaY4TH6O0hDVc/mEyMKPLvo1OCMWRVqTgr4rLMybtSAhJTRfngS32iTtK8/cDDA+D6quek0F0I6MhcZBf/8b5fBL0GBB2Kz0841Wenwi89zaK2oKbvCxUs1g0t0hgi4n0xacObbHLvwld1euYa0ANfjkVe/cmN5JRrfBSAsU2oWu6mQecMmFq6aEtx9db+7F9Pl/u3ztgSJXGbf/l/SL2Gs27F55TBAvqVSyj7nhKcs+HsQLpd61ezXONm8eBcR0/eHuHuONuwanKpHx2LyYKfLtsfPUocB1qZRl19fgJ9pQZSW3p5w3VnzLaXorL+zyJIBcMd43y6zbJDbG7lOE2HI5YemTNVqOAJ3ZBME1gzh0Nwe4G/AMmiD2gonAp5DFk7gOPkQ83FgH735d+dgV/tqac2ZG+fkCCxrPZqMB1Ar+aeOPgX3Bqfa5vxlS8="
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - deploy/*.yaml
  - deploy/crds/*.yaml
