apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  featureGates: 
    - "Snapshotting"
  imagePullPolicy: Always
  storagePools:
    - name: "nfs-backend"
      path: "/nfs-vol"
      snapshotPath: "/nfs-vol/snapshots"
      snapshotProvider: "reflink"
  workload:
    nodeSelector:
      kubernetes.io/os: linux
